apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
  labels:
    name: prometheus-node-exporter
    app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 9100
    name: scrape
    protocol: TCP
  selector:
    app: node-exporter
