apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    name: prometheus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: quay.io/prometheus/prometheus:v1.0.0
        command: ["/bin/prometheus"]
        args: [
             "-config.file=/etc/prometheus/prometheus.yml",
             "-storage.local.path=/prometheus",
             "-web.console.libraries=/etc/prometheus/console_libraries",
             "-web.console.templates=/etc/prometheus/consoles",
        ]
        name: prometheus
        resources:
          requests:
            memory: 2500Mi
            cpu: 500m
          limits:
            memory: 3000Mi
            cpu: 500m
        ports:
        - containerPort: 9090
          hostPort: 9090
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: "/prometheus"
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: prometheus-config

